# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycTB5FsTPJ8wMkXXdsVbBZUgIfysUZbX
"""

!pip install googletrans==4.0.0-rc1
!pip install gTTS
!pip install streamlit

import streamlit as st
from googletrans import Translator
from gtts import gTTS
from IPython.display import Audio, display

st.title("Asistente de Comunicación")

translator = Translator()

# Interfaz de usuario
source_text = st.text_input("Ingresa el texto que deseas traducir:")
target_language = st.text_input("Selecciona el idioma de destino (por ejemplo, 'es' para español):")

if st.button("Traducir y Reproducir"):
    # Traducción
    translation = translator.translate(source_text, dest=target_language)
    translated_text = translation.text

    # Síntesis de voz
    tts = gTTS(text=translated_text, lang=target_language)

    # Reproducir el audio
    st.audio(tts.get_audio_data(), format="audio/mp3")

from googletrans import Translator
from gtts import gTTS
from IPython.display import Audio, display

translator = Translator()

# Interfaz de usuario
source_text = input("Ingresa el texto que deseas traducir: ")
target_language = input("Selecciona el idioma de destino (por ejemplo, 'es' para español): ")

# Traducción
translation = translator.translate(source_text, dest="es")
translated_text = translation.text

# Síntesis de voz
tts = gTTS(text=translated_text, lang="es")

# Reproducir el audio
tts.save("translation.mp3")
display(Audio("translation.mp3", autoplay=True))