# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycTB5FsTPJ8wMkXXdsVbBZUgIfysUZbX
"""

!pip install googletrans==4.0.0-rc1
!pip install gTTS

from googletrans import Translator
from gtts import gTTS
from IPython.display import Audio, display

translator = Translator()

# Interfaz de usuario
source_text = input("Ingresa el texto que deseas traducir: ")
target_language = input("Selecciona el idioma de destino (por ejemplo, 'es' para español): ")

# Traducción
translation = translator.translate(source_text, dest="es")
translated_text = translation.text

# Síntesis de voz
tts = gTTS(text=translated_text, lang="es")

# Reproducir el audio
tts.save("translation.mp3")
display(Audio("translation.mp3", autoplay=True))