# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycTB5FsTPJ8wMkXXdsVbBZUgIfysUZbX
"""

import streamlit as st
from googletrans import Translator
from gtts import gTTS

# Título de la aplicación
st.title('Asistente para Comunicación')

# Sección para ingresar texto
with st.expander('Ingresa el Texto'):
    input_text = st.text_area('Escribe tu mensaje aquí:')
    if st.button('Traducir y Reproducir'):
        # Verifica si se ingresó texto
        if input_text:
            # Traduce el texto a un idioma deseado (por ejemplo, inglés)
            translator = Translator()
            translated_text = translator.translate(input_text, dest='en').text

            # Reproduce el texto traducido como audio
            tts = gTTS(text=translated_text, lang='en')
            st.audio(tts.get_audio_data(), format='audio/wav')
        else:
            st.warning('Por favor, ingresa un mensaje antes de traducir y reproducir.')

# Información adicional
st.info('Este asistente traducirá el texto ingresado al inglés y lo reproducirá como audio.')